name: Deploy and Test Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-v2:
    name: Deploy to v2.stepstokindness.org and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to v2.stepstokindness.org
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          cname: v2.stepstokindness.org

      - name: Run Tests
        run: |
          echo "============================="
          echo "🔍 Running tests on v2.stepstokindness.org"
          echo "============================="
          chmod +x scripts/test.sh
          ./scripts/test.sh || TEST_FAIL=1

          if [ "$TEST_FAIL" = "1" ]; then
            echo "❌ Some tests failed."
          else
            echo "✅ All tests passed successfully."
          fi

  deploy-production:
    name: Deploy to www.stepstokindness.org
    runs-on: ubuntu-latest
    needs: deploy-v2
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to www.stepstokindness.org
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          cname: www.stepstokindness.org
