name: Deploy StepsToKindness Static Site

on:
  push:
    branches:
      - '*-dev'
      - main-dev
      - master
      - 'v[0-9]*'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  determine-domain:
    runs-on: ubuntu-latest
    needs: checkout
    outputs:
      fqdn: ${{ steps.domain.outputs.fqdn }}
    steps:
      - name: Determine deployment domain
        id: domain
        run: |
          branch="${GITHUB_REF##*/}"
          if [[ "$branch" == "master" ]]; then
            echo "fqdn=stepstokindness.org" >> $GITHUB_OUTPUT
          elif [[ "$branch" == "main-dev" ]]; then
            echo "fqdn=dev.stepstokindness.org" >> $GITHUB_OUTPUT
          elif [[ "$branch" =~ ^v[0-9]+ ]]; then
            echo "fqdn=${branch}.stepstokindness.org" >> $GITHUB_OUTPUT
          elif [[ "$branch" =~ ^[a-zA-Z0-9_-]+-dev$ ]]; then
            name="${branch%-dev}"
            echo "fqdn=${name}.dev.stepstokindness.org" >> $GITHUB_OUTPUT
          else
            echo "fqdn=unknown.stepstokindness.org" >> $GITHUB_OUTPUT
          fi
          echo "Determined FQDN: $(cat $GITHUB_OUTPUT)"

  deploy:
    runs-on: ubuntu-latest
    needs: determine-domain
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          target_branch: gh-pages
          build_dir: .
          fqdn: ${{ needs.determine-domain.outputs.fqdn }}
          keep_history: false
          allow_empty_commit: true
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
